# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2fe2f8e5279b9bef4c016882a216a9169f44ca73c2cb47acaea0e49b1cf30f2c9b20177f7fd95789e35703fa07bb42bd2f426c2d42a151a83905a02d634e506

test:
  secret_key_base: 3eaa51148fa6e828d78b8f532bdf813634c6b3bc0a00d082cea87b4f5c17348b147fb00308bbc6cd2ab188f62fdfc284f4961f81c7b23fd625f60094f46240f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
